import React, { useMemo } from 'react';
import { useData } from '../../contexts/DataContext';
import { useLanguage } from '../../contexts/LanguageContext';

const ReportFooter: React.FC = () => {
    const { t } = useLanguage();
    const { selectedProperty, committeeMembers } = useData();

    const president = useMemo(() => {
        if (!selectedProperty) return null;
        const presidentPosition = t('president').toLowerCase();
        return committeeMembers.find(
            member => member.propertyId === selectedProperty.id && member.position.toLowerCase() === presidentPosition
        );
    }, [committeeMembers, selectedProperty, t]);

    if (!selectedProperty) return null;

    const { details } = selectedProperty;
    const { presidentSignature, associationStamp, associationName } = details;

    const qrCodeUrl = associationName 
        ? `https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(associationName)}&size=100x100&qzone=1` 
        : '';

    return (
        <div className="pt-8">
            <table style={{ width: '100%', tableLayout: 'fixed', borderCollapse: 'collapse' }}>
                <tbody>
                    <tr>
                        <td style={{ width: '33.33%', verticalAlign: 'bottom', textAlign: 'center', padding: '0 1rem' }}>
                            <div style={{ height: '5rem', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '0.25rem' }}>
                                {presidentSignature ? (
                                    <img src={presidentSignature} alt={t('president_signature')} style={{ maxHeight: '5rem', maxWidth: '100%', objectFit: 'contain' }} />
                                ) : (
                                    <div style={{ height: '5rem', width: '100%' }}></div>
                                )}
                            </div>
                            {president && <p className="text-sm font-semibold dark-text-fix leading-tight pb-1">{president.fullName}</p>}
                            <div style={{ paddingTop: '0.5rem', borderTop: '1px solid #9ca3af' }}>
                                <p className="text-xs dark-text-fix">{t('president_signature')}</p>
                            </div>
                        </td>
                        <td style={{ width: '33.33%', verticalAlign: 'bottom', textAlign: 'center', padding: '0 1rem' }}>
                            <div style={{ height: '6rem', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                {associationStamp ? (
                                    <img src={associationStamp} alt={t('association_stamp')} style={{ maxHeight: '6rem', maxWidth: '100%', objectFit: 'contain' }} />
                                ) : (
                                    <div style={{ height: '6rem', width: '100%' }}></div>
                                )}
                            </div>
                            <p style={{ paddingTop: '0.5rem', borderTop: '1px solid #9ca3af', marginTop: '0.5rem' }} className="text-xs dark-text-fix">{t('association_stamp')}</p>
                        </td>
                        <td style={{ width: '33.33%', verticalAlign: 'bottom', textAlign: 'center', padding: '0 1rem' }}>
                            <div style={{ height: '6rem', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                {qrCodeUrl ? (
                                    <img src={qrCodeUrl} alt={associationName || 'QR Code'} style={{ height: '6rem', width: '6rem', objectFit: 'contain' }} />
                                ) : (
                                    <div style={{ height: '6rem', width: '100%' }}></div>
                                )}
                            </div>
                            <p style={{ paddingTop: '0.5rem', borderTop: '1px solid #9ca3af', marginTop: '0.5rem' }} className="text-xs dark-text-fix">{t('association_qr')}</p>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div className="page-number-container mt-2">
                {/* This content is generated by CSS for printing */}
            </div>
        </div>
    );
};

export default ReportFooter;